name: flutter_application_3
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  #- DEPENDENDIES OF FIREBASE
  #- firebase core: sirve para conectarse con el proyecto en general 
  firebase_core: ^2.15.0
  # - es la base de datos
  cloud_firestore: ^4.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
