// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmTHXgpfuB-PrkYhuepqdZ9SBzqtuYvvU',
    appId: '1:749906237943:web:88c58dd1a13e46f90136f2',
    messagingSenderId: '749906237943',
    projectId: 'account-tracker-firebase-5b94c',
    authDomain: 'account-tracker-firebase-5b94c.firebaseapp.com',
    storageBucket: 'account-tracker-firebase-5b94c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHXuN3UGHFGIhwdXBE_VApELJ9BEB8W4',
    appId: '1:749906237943:android:af95151bd5849c6f0136f2',
    messagingSenderId: '749906237943',
    projectId: 'account-tracker-firebase-5b94c',
    storageBucket: 'account-tracker-firebase-5b94c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTaIaB09vRtYXE-lM7IMVTMBW2LkLNU08',
    appId: '1:749906237943:ios:87c96cc80fe84c140136f2',
    messagingSenderId: '749906237943',
    projectId: 'account-tracker-firebase-5b94c',
    storageBucket: 'account-tracker-firebase-5b94c.appspot.com',
    iosClientId: '749906237943-om9pn5c8hqgdsp0oo55sffisddu7fs0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTaIaB09vRtYXE-lM7IMVTMBW2LkLNU08',
    appId: '1:749906237943:ios:87c96cc80fe84c140136f2',
    messagingSenderId: '749906237943',
    projectId: 'account-tracker-firebase-5b94c',
    storageBucket: 'account-tracker-firebase-5b94c.appspot.com',
    iosClientId: '749906237943-om9pn5c8hqgdsp0oo55sffisddu7fs0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
